### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by EnterpriseWide** [kgiszewski/LearnUmbraco7#19]
There are great reasons to create a Site Settings Container in the way you have under a Domain Node but I get a lot of mileage out of having a Site Settings Tab on the Site Node and using recursive property calls in the razor files. This isn't clear from the notes and IMHO we are educating people on best practice so hopefully my idea of this as a best practice is ok. I know it might be slightly off topic but do you think it is valuable to show Site Settings Tab and Site Settings Nodes in the images.
https://github.com/kgiszewski/LearnUmbraco7/tree/master/Chapter%2012%20-%20Multisite%20Configuration

**Comment by kgiszewski** [comment]
I think showing multiple ways to handle the site settings would be beneficial to others. I welcome a pull request to show how you handle this.

**Comment by kgiszewski** [comment]
Closing, feel free to reopen and send a pull request if you want to offer another way to do it.
