### ISSUE TITLE
Write How to organize Visual Studio 2013 Solution to create Umbraco addons

### ISSUE THREAD

**Issue by biapar** [kgiszewski/LearnUmbraco7#20]
Write How to organize Visual Studio 2013 Solution to create Umbraco addons

**Comment by kgiszewski** [comment]
Thinking this could go in Appendix C and include items such as:
- Show Solution setup
- Where to put `source`
- Where to put `.gitignore` (and include a sample .gitignore) and explain what should not go into source control
- Where to put `projects` (and show multiple projects in one solution)
- Where to put dll's installed from the built-in package manager
- Where to put non-.NET items like `gruntfile.js`

**Comment by biapar** [comment]
Hi, 

sorry, I made a mistake. I would know how to organize a Vs2013 solution to build a web app on Umbraco...-:)

**Comment by kgiszewski** [comment]
I'll write this one up in the near future.

**Comment by biapar** [comment]
Have you some guidelines? There are a lots metods, but any official guide how to organize the solution. Which type of project will be where I'll add custom controllers, views, etc? And for backoffice api?

**Comment by kgiszewski** [comment]
Hopefully you find this helpful. Let me know if it needs more.
