### ISSUE TITLE
24days.in

### ISSUE THREAD

**Issue by blachawk** [kgiszewski/LearnUmbraco7#48]
I'm not sure what is the full intent of http://24days.in, but

1.  The site appears not to work
2.  If you attempt to access the /umbraco backoffice area, it requires a username and password.  

This link can be found on Chapter 01, 02-Community.md

**Comment by honzabilek4** [comment]
Hi,
the correct link is: [http://24days.in/umbraco-cms/](http://24days.in/umbraco-cms/)
This redirects you to the year 2016. However the series start in 2012.

**Comment by kgiszewski** [comment]
Thanks for the report. I've updated it!
