### ISSUE TITLE
Help with understanding Multisite Configuration in Chapter 12

### ISSUE THREAD

**Issue by blachawk** [kgiszewski/LearnUmbraco7#52]
The author wrote...

> 
> - Create a Site document type (or whatever you name it) that will reside on root of your content section for each of your sites.
> -  Use relative paths when using data types such as the multinode tree picker.
> -  Create a Home page under your Site node and all pages as children under the Home node.
> -  Assign a domain to each Home node.
> -  Consider creating a Site Settings document type to hold settings for each website.
> 

## My questions based on bullets above:
* Do we need to create a `Site` template along with the `Site` document type? or just have the document type itself?
* `RenderBody()`, does not work on a `Site` template. It belongs to a Master template.  So do I need to create an additional Master template?
* Where do we write relative paths with the `Multinode tree picker`? Show me an example of where a relative path should be written.
* Before we get to the part of having a home page, do we need to create a `Home` document type with `Home` template? and then make this `Home` template a child of the `Site` template?

I apologize if this sounds like 1st grade Umbraco questions - I just want to make sure I'm on the same page.  

Thanks!

**Comment by kgiszewski** [comment]
No worries :)

You might also try out http://our.umbraco.org

I use Razor templates, each site has a base.cshtml (with a RenderBody() on each).
`Site` is a node only, no template.
`SiteSettings` is the same, no template.
Each site should have it's own unique HomePage doctype as each site will have unique inputs. Each should have exactly one template.

I think you're confusing templates and doctypes.

Doctypes are what hold the input controls. Each doctype can have one or more templates (though you should try to keep it 1 to 1). Doctypes then are used to create instances of content. Doctypes can be allowed as children of other doctypes. This drives the 'create' context menu options.

MNTP relative paths are configured on the MNTP data types in the `developer` section.

![sample](https://user-images.githubusercontent.com/4653907/35359425-0c8baf8c-0128-11e8-9e56-6fd85d699d7d.jpg)

**Comment by kgiszewski** [comment]
Some videos you may be interested in: https://www.youtube.com/playlist?list=PL9uZoG6lhmR1ZZ7lKjINyYEAviZb40vLI

**Comment by blachawk** [comment]
I appreciate the support, but we're not on the same page. I know the basics of setting up a document type and  templates in Umbraco.  I just need clarity on your 4 bullet points mentioned above.  For example, is the Site document type you mention in the bullet list, associated to a template?

**Comment by blachawk** [comment]
Love the strategy you have going between doc types and templates.  I will give this a shot as it may help out a project I'm building.  Thanks!

**Comment by blachawk** [comment]
@kgiszewski
I have this  now working on my local development environment.  Thanks for the visuals.  They helped out a lot!

**Comment by kgiszewski** [comment]
Need more visuals? I made you a video: https://www.youtube.com/watch?v=0H2o_mwhRhI

**Comment by kgiszewski** [comment]
@blachawk oh and you're a fellow Hoosier! Best of luck sir.
